### ISSUE TITLE
Nuget update?

### ISSUE THREAD

**Issue by RobertDM** [MisinformedDNA/Elmah.AzureTableStorage#17]
Appreciate your recent updating the Azure Configuration Manager libraries to 3.1.0.0 for this project.

Are you going to update the version on nuget.org?

**Comment by abatishchev** [comment]
Can't you just configure bindings redirect?

**Comment by RobertDM** [comment]
Unfortunately the issue is that Microsoft changed the namespace, so it is not a simple version redirect

**Comment by abatishchev** [comment]
Oh, right, forgot about it.

@MisinformedDNA can you please upgrade all packages to latest?

**Comment by MisinformedDNA** [comment]
https://github.com/MisinformedDNA/Elmah.AzureTableStorage/pull/14 includes upgrading the Azure packages. I'll upgrade Nuget as soon as that is committed.

**Comment by MisinformedDNA** [comment]
Done.
